# Class 6 – Importing Libraries and Working with NumPy

## 1. Warm-Up

### Why do we need external libraries in Python?

Python is powerful, but not all features are built-in. External libraries help you do more with less code.

### Built-in vs. External Libraries

- **Built-in:** Available by default. E.g., `math`, `datetime`
- **External:** You need to install them. E.g., `NumPy`, `Pandas`, `Matplotlib`

### Popular Python Libraries

- `NumPy`: Numerical operations
- `Pandas`: Data manipulation
- `Matplotlib`: Data visualization

### Quick Demo Using a Built-in Library


In [1]:
import math
print(math.sqrt(16))  # Output: 4.0

4.0


## 2. Installing and Importing Libraries

### What Are Python Libraries?

Think of libraries as toolboxes. Instead of building tools from scratch, you use pre-built ones.

### Installing Libraries

Use `pip install` from the terminal (not inside Jupyter):

```bash
pip install numpy
```

### Importing Libraries

Use `import` to bring a library into your code.


In [1]:
# Importing NumPy
import numpy as np 

# Check version
print("NumPy version:", np.__version__)

NumPy version: 1.26.3


## 3. Understanding NumPy Arrays

### Python Lists vs NumPy Arrays

- Python lists are flexible but slower.
- NumPy arrays are faster and used for scientific computing.

### Real-life Analogy:

Think of Python lists like a regular car and NumPy arrays like a race car—built for speed and performance.

### Creating NumPy Arrays


In [3]:
import numpy as np

# Creating a 1D NumPy array
arr = np.array([1, 2, 3, 4, 5])
print("Array:", arr)
print("Type:", type(arr))  # <class 'numpy.ndarray'>

Array: [1 2 3 4 5]
Type: <class 'numpy.ndarray'>


In [4]:
print(arr.ndim)


1


In [16]:
arr.shape

(5,)

In [ ]:
array = np.array([[1,2],[3,4]])
print(array)
array.ndim

[[1 2]
 [3 4]]


(2, 2)

In [21]:
array.shape

(2, 2)

In [22]:
array.dtype

dtype('int32')

In [23]:
array.nbytes

16

In [4]:
# Creating a 2D NumPy array (Matrix)
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("Matrix:", matrix)

Matrix: [[1 2 3]
 [4 5 6]]


In [25]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [ ]:
# Accessing the elements:
a[1,5] # [ row, column]

13

In [ ]:
# Accessing and modifying elements
arr = np.array([1, 2, 3, 4, 5])
print("Array:", arr)

print("Third element of arr:", arr[2])  # Output: 3

arr[1] = 10
print("Modified array:", arr)  # Output: [1, 10, 3, 4, 5]

Array: [1 2 3 4 5]
Third element of arr: 3
Modified array: [ 1 10  3  4  5]


### Activity

Create a NumPy array and experiment with indexing and slicing.


In [6]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

a[1,:]


[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


array([ 8,  9, 10, 11, 12, 13, 14])

In [7]:
print(a[:,3])

[ 4 11]


In [ ]:
a[0, 1:6:2] # start_index : stop_index-1 : step_interval

array([2, 4, 6])

In [34]:
a[:,2]= 5
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 13 14]]


In [35]:
a[:,6]= [1,2]
print(a)

[[ 1  2  5  4  5  6  1]
 [ 8  9  5 11 12 13  2]]


In [3]:
# Activity
activity_array = np.array([10, 20, 30, 40, 50])
print("Original:", activity_array)
print("First three elements:", activity_array[:3])

Original: [10 20 30 40 50]
First three elements: [10 20 30]


In [8]:
# 3D array

b = np.array([[[1,2],[3,4],[5,6]], [[5,6],[7,8],[6,1]]])
print(b)

[[[1 2]
  [3 4]
  [5 6]]

 [[5 6]
  [7 8]
  [6 1]]]


In [37]:
b[1,1,1]

8

# Initializing Different Types of Arrays

In [38]:
np.zeros(3)

array([0., 0., 0.])

In [39]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [40]:
np.zeros((2,3,3))

array([[[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]])

In [9]:
np.ones(2)

array([1., 1.])

In [41]:
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [42]:
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [43]:
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [10]:
np.random.rand(4,2)

array([[0.58523502, 0.46421113],
       [0.69870877, 0.75988826],
       [0.00636589, 0.85049656],
       [0.28163247, 0.86443014]])

In [45]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## 4. Mathematical Operations on Arrays

### Element-wise Operations

Each element operates with its counterpart.

### Broadcasting

Operations between arrays of different shapes.

### Aggregation Functions

Functions like sum, mean, max that work across the array.


In [48]:
a = np.array([1,2,3,4])
a+2

array([3, 4, 5, 6])

In [ ]:
# Element-wise arithmetic
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print("Sum:", arr1 + arr2)       # [5 7 9]
print("Product:", arr1 * arr2)   # [4 10 18]

In [ ]:
# Broadcasting
arr = np.array([1, 2, 3])
print("Broadcasted:", arr * 2)   # [2 4 6]

In [ ]:
# Aggregation functions
numbers = np.array([10, 20, 30, 40])
print("Mean:", np.mean(numbers))  # 25.0
print("Sum:", np.sum(numbers))    # 100
print("Max:", np.max(numbers))    # 40

### Activity

Multiply two arrays and calculate the sum.


In [11]:
# Activity
a = np.array([2, 4, 6])
b = np.array([1, 3, 5])
product = a * b
print("Element-wise product:", product)
print("Sum of result:", np.sum(product))

Element-wise product: [ 2 12 30]
Sum of result: 44


## 5. Matrix Operations Using NumPy

### Matrix Multiplication

Use `np.dot()` or `@` for matrix multiplication.

### Transpose

Swap rows with columns.

### Identity Matrix

Square matrix with 1s on diagonal and 0s elsewhere.


In [12]:
# Matrix multiplication
A = np.array([[1, 2], [3, 4]]) # 2*2
B = np.array([[5, 6], [7, 8]])# 2*2
C = np.matmul(A, B) # np.dot(A,B)
print("Matrix C:", C)

Matrix C: [[19 22]
 [43 50]]


In [13]:
A = np.array([[1, 2], [3, 4]])
print(A)

[[1 2]
 [3 4]]


In [14]:
# Transpose of a matrix
print("Transpose of A:", A.T)

Transpose of A: [[1 3]
 [2 4]]


In [ ]:
# Identity matrix
I = np.eye(3)
print("3x3 Identity Matrix:", I)

### Activity

Multiply two matrices and find their transpose.


In [ ]:
# Activity
X = np.array([[2, 0], [1, 3]])
Y = np.array([[4, 1], [2, 2]])
result = np.dot(X, Y)
print("Matrix multiplication result:", result)
print("Transpose:", result.T)

## 6. Wrap-Up and Homework

### Recap

- Libraries extend Python's capabilities.
- NumPy arrays are more efficient than lists for numerical tasks.
- Mathematical and matrix operations are easy with NumPy.

### Homework

1. Write a Python program to create a NumPy array and perform arithmetic operations.
2. Write a program that multiplies two matrices and finds their transpose.


In [ ]:
import numpy as np

# Create a NumPy array
array1 = np.array([10, 20, 30, 40, 50])
array2 = np.array([1, 2, 3, 4, 5])

# Display the original arrays
print("Array 1:", array1)
print("Array 2:", array2)

# Perform arithmetic operations
addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2
division = array1 / array2

# Display the results
print("\nAddition:", addition)
print("Subtraction:", subtraction)
print("Multiplication:", multiplication)
print("Division:", division)


In [ ]:
import numpy as np

# Define two matrices
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

# Multiply the matrices
product = np.dot(A, B)

# Find the transpose of the result
transpose = product.T

# Display the matrices and results
print("Matrix A:\n", A)
print("Matrix B:\n", B)
print("\nProduct of A and B:\n", product)
print("\nTranspose of the product:\n", transpose)
